
services:
  cloudhoster:
    build:
      context: ./cloudhoster
    container_name: cloudhoster
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "110:110"
    volumes:
      - wordpress_data:/var/www/html
      - ./cloudhoster/conf:/config
      - ./cloudhoster/scripts/roundcube-init.sh:/config/roundcube-init.sh
      - ./cloudhoster/scripts/php-fpm-init.sh:/config/php-fpm-init.sh
      - ./cloudhoster/scripts/start.sh:/start.sh
    entrypoint: ["/start.sh"]
    networks:
      - internal

  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cloudhoster/conf/roundcube.conf:/etc/roundcube/config.inc.php
    networks:
      - internal

volumes:
  db_data:
  wordpress_data:

networks:
  internal:
    driver: bridge